import type { CategorySlug, CategoryMeta } from '@/lib/types'

export const CATEGORY_META: Record<CategorySlug, CategoryMeta> = {
  telecom: {
    label: '통신',
    icon: 'Smartphone',
    color: '#E6F1FB',
    textColor: '#0C447C',
    subcategories: ['휴대폰', '인터넷', 'IPTV', '기업회선'],
    providers: ['SKT', 'KT', 'LG U+', 'SKB', 'KT인터넷', '알뜰폰'],
  },
  utility: {
    label: '공과금',
    icon: 'Zap',
    color: '#EAF3DE',
    textColor: '#27500A',
    subcategories: ['전기', '수도', '도시가스', '관리비', '주차'],
    providers: ['한국전력', '서울시 수도사업소', '도시가스'],
  },
  insurance: {
    label: '보험',
    icon: 'Shield',
    color: '#FAEEDA',
    textColor: '#633806',
    subcategories: ['실손', '건강', '암', '치아', '운전자', '자동차', '화재', '종신'],
    providers: ['삼성화재', '현대해상', 'KB손보', '메리츠화재', '한화생명'],
  },
  subscription: {
    label: '구독',
    icon: 'Play',
    color: '#EEEDFE',
    textColor: '#3C3489',
    subcategories: ['OTT', '음악', '클라우드', '뉴스', 'AI', '소프트웨어'],
    providers: ['넷플릭스', '유튜브', '디즈니+', '티빙', '왓챠', 'ChatGPT', 'Adobe'],
  },
  rental: {
    label: '렌탈',
    icon: 'Settings',
    color: '#FBEAF0',
    textColor: '#72243E',
    subcategories: ['정수기', '공기청정기', '비데', '안마의자', '렌터카'],
    providers: ['코웨이', '청호나이스', '쿠쿠', '바디프랜드'],
  },
  tax: {
    label: '세금',
    icon: 'Receipt',
    color: '#FCEBEB',
    textColor: '#791F1F',
    subcategories: ['재산세', '자동차세', '종합소득세', '부가세', '주민세'],
    providers: ['국세청', '지방자치단체'],
  },
  penalty: {
    label: '과태료',
    icon: 'AlertTriangle',
    color: '#FFF3E0',
    textColor: '#7C4700',
    subcategories: ['주정차', '속도위반', '신호위반', '환경'],
    providers: [],
  },
  vehicle: {
    label: '차량',
    icon: 'Car',
    color: '#E8F5E9',
    textColor: '#1B5E20',
    subcategories: ['자동차보험', '자동차세', '정기검사', '하이패스'],
    providers: ['삼성화재', '현대해상', '한국도로공사'],
  },
  housing: {
    label: '주거',
    icon: 'Home',
    color: '#F3E5F5',
    textColor: '#4A148C',
    subcategories: ['월세', '전세대출이자', '관리비', '장기수선'],
    providers: [],
  },
  finance: {
    label: '금융',
    icon: 'CreditCard',
    color: '#E0F7FA',
    textColor: '#006064',
    subcategories: ['대출이자', '카드연회비', '적금'],
    providers: [],
  },
  business: {
    label: '사업',
    icon: 'Briefcase',
    color: '#FFF8E1',
    textColor: '#F57F17',
    subcategories: ['도메인', '서버', '클라우드', 'SaaS', '임대료', 'PG'],
    providers: ['AWS', 'GCP', 'Vercel', 'Cloudflare', 'Cafe24'],
  },
  other: {
    label: '기타',
    icon: 'MoreHorizontal',
    color: '#F1EFE8',
    textColor: '#444441',
    subcategories: [],
    providers: [],
  },
}
